version: '2'
services:
  db-data: # dummy container to avoid loose of Mongo DB data on container restart
    container_name: db-data
    image: mongo
    volumes:
      - /data/mongo:/data/db/
    entrypoint:
      /bin/true # prevent running MongoDB instance within this container

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes_from:
      - db-data

  api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    links:
      - mongodb:mongodb
    ports:
      - 4000:4000
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./:/usr/src/app
    user: root